ReservationSystem: ReservationSystem.o main.o Flight.o Reservation.o
	g++ ReservationSystem.o main.o Flight.o Reservation.o -o ReservationSystem

ReservationSystem.o: ReservationSystem.cpp
	g++ -c ReservationSystem.cpp

main.o: main.cpp
	g++ -c main.cpp

Flight.o: Flight.cpp
	g++ -c Flight.cpp

Reservation.o: Reservation.cpp
	g++ -c Reservation.cpp
